#include "Symbol.hpp"

std::string toString(Symbol s) {
    switch (s) {
        case Symbol::intcon: return "intcon";
        case Symbol::realcon: return "realcon";
        case Symbol::charcon: return "charcon";
        case Symbol::string: return "string";
        case Symbol::notsy: return "notsy";
        case Symbol::plus: return "plus";
        case Symbol::minus: return "minus";
        case Symbol::times: return "times";
        case Symbol::idiv: return "idiv";
        case Symbol::rdiv: return "rdiv";
        case Symbol::imod: return "imod";
        case Symbol::andsy: return "andsy";
        case Symbol::orsy: return "orsy";
        case Symbol::eql: return "eql";
        case Symbol::neq: return "neq";
        case Symbol::gtr: return "gtr";
        case Symbol::geq: return "geq";
        case Symbol::lss: return "lss";
        case Symbol::leq: return "leq";
        case Symbol::lparent: return "lparent";
        case Symbol::rparent: return "rparent";
        case Symbol::lbrack: return "lbrack";
        case Symbol::rbrack: return "rbrack";
        case Symbol::comma: return "comma";
        case Symbol::semicolon: return "semicolon";
        case Symbol::period: return "period";
        case Symbol::colon: return "colon";
        case Symbol::becomes: return "becomes";
        case Symbol::constsy: return "constsy";
        case Symbol::typesy: return "typesy";
        case Symbol::varsy: return "varsy";
        case Symbol::functionsy: return "functionsy";
        case Symbol::proceduresy: return "proceduresy";
        case Symbol::arraysy: return "arraysy";
        case Symbol::recordsy: return "recordsy";
        case Symbol::programsy: return "programsy";
        case Symbol::ident: return "ident";
        case Symbol::beginsy: return "beginsy";
        case Symbol::ifsy: return "ifsy";
        case Symbol::casesy: return "casesy";
        case Symbol::repeatsy: return "repeatsy";
        case Symbol::whilesy: return "whilesy";
        case Symbol::forsy: return "forsy";
        case Symbol::endsy: return "endsy";
        case Symbol::elsesy: return "elsesy";
        case Symbol::untilsy: return "untilsy";
        case Symbol::ofsy: return "ofsy";
        case Symbol::dosy: return "dosy";
        case Symbol::tosy: return "tosy";
        case Symbol::downtosy: return "downtosy";
        case Symbol::thensy: return "thensy";
        case Symbol::comment: return "comment";
        case Symbol::unknown: return "unknown";

        case Symbol::PROGRAM: return "<program>";
        case Symbol::PROGRAM_HEADER: return "<program-header>";
        case Symbol::DECLARATION_PART: return "<declaration-part>";
        case Symbol::CONST_DECLARATION: return "<const-declaration>";
        case Symbol::CONSTANT: return "<constant>";
        case Symbol::TYPE_DECLARATION: return "<type-declaration>";
        case Symbol::VAR_DECLARATION: return "<var-declaration>";
        case Symbol::IDENTIFIER_LIST: return "<identifier-list>";
        case Symbol::TYPE: return "<type>";
        case Symbol::ARRAY_TYPE: return "<array-type>";
        case Symbol::RANGE: return "<range>";
        case Symbol::ENUMERATED: return "<enumerated>";
        case Symbol::RECORD_TYPE: return "<record-type>";
        case Symbol::FIELD_LIST: return "<field-list>";
        case Symbol::FIELD_PART: return "<field-part>";
        case Symbol::SUBPROGRAM_DECLARATION: return "<subprogram-declaration>";
        case Symbol::PROCEDURE_DECLARATION: return "<procedure-declaration>";
        case Symbol::FUNCTION_DECLARATION: return "<function-declaration>";
        case Symbol::BLOCK: return "<block>";
        case Symbol::FORMAL_PARAMETER_LIST: return "<formal-parameter-list>";
        case Symbol::PARAMETER_GROUP: return "<parameter-group>";
        case Symbol::COMPOUND_STATEMENT: return "<compound-statement>";
        case Symbol::STATEMENT_LIST: return "<statement-list>";
        case Symbol::STATEMENT: return "<statement>";
        case Symbol::VARIABLE: return "<variable>";
        case Symbol::COMPONENT_VARIABLE: return "<component-variable>";
        case Symbol::INDEX_LIST: return "<index-list>";
        case Symbol::ASSIGNMENT_STATEMENT: return "<assignment-statement>";
        case Symbol::IF_STATEMENT: return "<if-statement>";
        case Symbol::CASE_STATEMENT: return "<case-statement>";
        case Symbol::CASE_BLOCK: return "<case-block>";
        case Symbol::WHILE_STATEMENT: return "<while-statement>";
        case Symbol::REPEAT_STATEMENT: return "<repeat-statement>";
        case Symbol::FOR_STATEMENT: return "<for-statement>";
        case Symbol::PROCEDURE_FUNCTION_CALL: return "<procedure/function-call>";
        case Symbol::PARAMETER_LIST: return "<parameter-list>";
        case Symbol::EXPRESSION: return "<expression>";
        case Symbol::SIMPLE_EXPRESSION: return "<simple-expression>";
        case Symbol::TERM: return "<term>";
        case Symbol::FACTOR: return "<factor>";
        case Symbol::RELATIONAL_OPERATOR: return "<relational-operator>";
        case Symbol::ADDITIVE_OPERATOR: return "<additive-operator>";
        case Symbol::MULTIPLICATIVE_OPERATOR: return "<multiplicative-operator>";
        default: return "unknown";
    }
}

bool isToken(Symbol s){
    return s < Symbol::PROGRAM || s == Symbol::unknown;
}

Symbol toSymbol(const std::string &s) {
    if (s == "intcon") return Symbol::intcon;
    if (s == "realcon") return Symbol::realcon;
    if (s == "charcon") return Symbol::charcon;
    if (s == "string") return Symbol::string;
    if (s == "notsy") return Symbol::notsy;
    if (s == "plus") return Symbol::plus;
    if (s == "minus") return Symbol::minus;
    if (s == "times") return Symbol::times;
    if (s == "idiv") return Symbol::idiv;
    if (s == "rdiv") return Symbol::rdiv;
    if (s == "imod") return Symbol::imod;
    if (s == "andsy") return Symbol::andsy;
    if (s == "orsy") return Symbol::orsy;
    if (s == "eql") return Symbol::eql;
    if (s == "neq") return Symbol::neq;
    if (s == "gtr") return Symbol::gtr;
    if (s == "geq") return Symbol::geq;
    if (s == "lss") return Symbol::lss;
    if (s == "leq") return Symbol::leq;
    if (s == "lparent") return Symbol::lparent;
    if (s == "rparent") return Symbol::rparent;
    if (s == "lbrack") return Symbol::lbrack;
    if (s == "rbrack") return Symbol::rbrack;
    if (s == "comma") return Symbol::comma;
    if (s == "semicolon") return Symbol::semicolon;
    if (s == "period") return Symbol::period;
    if (s == "colon") return Symbol::colon;
    if (s == "becomes") return Symbol::becomes;
    if (s == "constsy") return Symbol::constsy;
    if (s == "typesy") return Symbol::typesy;
    if (s == "varsy") return Symbol::varsy;
    if (s == "functionsy") return Symbol::functionsy;
    if (s == "proceduresy") return Symbol::proceduresy;
    if (s == "arraysy") return Symbol::arraysy;
    if (s == "recordsy") return Symbol::recordsy;
    if (s == "programsy") return Symbol::programsy;
    if (s == "ident") return Symbol::ident;
    if (s == "beginsy") return Symbol::beginsy;
    if (s == "ifsy") return Symbol::ifsy;
    if (s == "casesy") return Symbol::casesy;
    if (s == "repeatsy") return Symbol::repeatsy;
    if (s == "whilesy") return Symbol::whilesy;
    if (s == "forsy") return Symbol::forsy;
    if (s == "endsy") return Symbol::endsy;
    if (s == "elsesy") return Symbol::elsesy;
    if (s == "untilsy") return Symbol::untilsy;
    if (s == "ofsy") return Symbol::ofsy;
    if (s == "dosy") return Symbol::dosy;
    if (s == "tosy") return Symbol::tosy;
    if (s == "downtosy") return Symbol::downtosy;
    if (s == "thensy") return Symbol::thensy;
    if (s == "comment") return Symbol::comment;
    if (s == "unknown") return Symbol::unknown;

    if (s == "<program>") return Symbol::PROGRAM;
    if (s == "<program-header>") return Symbol::PROGRAM_HEADER;
    if (s == "<declaration-part>") return Symbol::DECLARATION_PART;
    if (s == "<const-declaration>") return Symbol::CONST_DECLARATION;
    if (s == "<constant>") return Symbol::CONSTANT;
    if (s == "<type-declaration>") return Symbol::TYPE_DECLARATION;
    if (s == "<var-declaration>") return Symbol::VAR_DECLARATION;
    if (s == "<identifier-list>") return Symbol::IDENTIFIER_LIST;
    if (s == "<type>") return Symbol::TYPE;
    if (s == "<array-type>") return Symbol::ARRAY_TYPE;
    if (s == "<range>") return Symbol::RANGE;
    if (s == "<enumerated>") return Symbol::ENUMERATED;
    if (s == "<record-type>") return Symbol::RECORD_TYPE;
    if (s == "<field-list>") return Symbol::FIELD_LIST;
    if (s == "<field-part>") return Symbol::FIELD_PART;
    if (s == "<subprogram-declaration>") return Symbol::SUBPROGRAM_DECLARATION;
    if (s == "<procedure-declaration>") return Symbol::PROCEDURE_DECLARATION;
    if (s == "<function-declaration>") return Symbol::FUNCTION_DECLARATION;
    if (s == "<block>") return Symbol::BLOCK;
    if (s == "<formal-parameter-list>") return Symbol::FORMAL_PARAMETER_LIST;
    if (s == "<parameter-group>") return Symbol::PARAMETER_GROUP;
    if (s == "<compound-statement>") return Symbol::COMPOUND_STATEMENT;
    if (s == "<statement-list>") return Symbol::STATEMENT_LIST;
    if (s == "<statement>") return Symbol::STATEMENT;
    if (s == "<variable>") return Symbol::VARIABLE;
    if (s == "<component-variable>") return Symbol::COMPONENT_VARIABLE;
    if (s == "<index-list>") return Symbol::INDEX_LIST;
    if (s == "<assignment-statement>") return Symbol::ASSIGNMENT_STATEMENT;
    if (s == "<if-statement>") return Symbol::IF_STATEMENT;
    if (s == "<case-statement>") return Symbol::CASE_STATEMENT;
    if (s == "<case-block>") return Symbol::CASE_BLOCK;
    if (s == "<while-statement>") return Symbol::WHILE_STATEMENT;
    if (s == "<repeat-statement>") return Symbol::REPEAT_STATEMENT;
    if (s == "<for-statement>") return Symbol::FOR_STATEMENT;
    if (s == "<procedure/function-call>") return Symbol::PROCEDURE_FUNCTION_CALL;
    if (s == "<parameter-list>") return Symbol::PARAMETER_LIST;
    if (s == "<expression>") return Symbol::EXPRESSION;
    if (s == "<simple-expression>") return Symbol::SIMPLE_EXPRESSION;
    if (s == "<term>") return Symbol::TERM;
    if (s == "<factor>") return Symbol::FACTOR;
    if (s == "<relational-operator>") return Symbol::RELATIONAL_OPERATOR;
    if (s == "<additive-operator>") return Symbol::ADDITIVE_OPERATOR;
    if (s == "<multiplicative-operator>") return Symbol::MULTIPLICATIVE_OPERATOR;

    return Symbol::unknown;
}